config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :users, only: [:show, :index, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true
  validates :name, length: { in: 2..20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,only: [:edit]

  def new
  	@book = Book.new
  end

  def create
  	@newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
  	if @newbook.save
      flash[:notice] = "Book was successfully created."
  	  redirect_to book_path(@newbook.id)
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index
    end
  end

  def index
    @newbook = Book.new
  	@books = Book.all
    @user = current_user
  end

  def show
  	@newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book was successfully deleted."
    redirect_to books_path
  end

  private
  def book_params
  	  params.require(:book).permit(:title, :body)
  end
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    if @user.id != current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,only: [:edit]

  def show
    @newbook = Book.new
  	@user = User.find(params[:id])
  	@books = @user.books
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @newbook = Book.new
    @book = Book
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
    def user_params
  	  params.require(:user).permit(:name, :introduction, :profile_image)
    end
    def correct_user
      @user = User.find(params[:id])
      if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-8">
  <p id="notice"><%= notice %></p>
  <h2>Editing Book</h2>
  <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <h2><%= @book.errors.count %>error</h2>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Update Book' %>
  <% end %>
  <%= link_to 'Show', book_path(@book) %>
  <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
  <%= render 'users/list', user: @user, book: @newbook %>
<div class="col-xs-9">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Body</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
            <%= attachment_image_tag book.user, :profile_image, size:"30x30", format: 'jpeg', class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to book do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/list', user: @user, book: @newbook %>
      <div class="col-xs-9">
        <h3>Book detail</h3>
        <table class="table table-striped">
          <thead>
            <tr>
      	      <th>
                <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, format: 'jpeg', class: "img-circle pull-left profile-img" %>
                <br><br><%= @user.name %>
                <% end %>
              </th>
      	      <th><p><%= @book.title %></p></th>
              <th><p><%= @book.body %></p></th>
                <%if @user.id == current_user.id %>
              <th>
                <button type="button" class="btn btn-success">
                <%= link_to 'Edit', edit_book_path(@book) %></button>
              </th>
              <th>
            <button type="button" class="btn btn-danger">
            <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' } %></button>
          </th>
        <% end %>
      </tr>
    </thead>
  </table>
</div>
</div>
</div>

app/views/home/about.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4">
  <h2>Welcome to Bookers!</h2>
</div>
<div class="col-lg-4"></div>

app/views/home/top.html.erb
<div class="col-lg-4">
  <p id="notice"><%= notice %></p>
</div>
<div class="col-lg-4">
  <h1>welcome to Bookers !!</h1>
  <h4>In Bookers,<br>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</h4>
  <div class="btn-group-vertical" role="group">
    <button type="button" class="btn btn-default" >
      <%= link_to 'Log in', new_user_session_path %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to 'Sign Up', new_user_registration_path %>
    </button>
  </div>
</div>
<div class="col-lg-4"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <nav class='nav navbar-nav navbar-left' >
        <h4>Bookers</h4>
      </nav>
      <ul class="nav nav-pills navbar-inverse" data-animations="zoomIn fadeIn fadeInUp fadeIn">
        <%if user_signed_in? %>
          <li class=""></li>
          <li class=""><%= link_to 'Home', user_path(current_user.id) %></li>
          <li class=""><%= link_to 'Users', users_path %></li>
          <li class=""><%= link_to 'Books', books_path %></li>
          <li class=""><%= link_to "logout", destroy_user_session_path, :method => :delete%></li>
        <% else %>
          <li class=""><%= link_to 'Home', root_path %></li>
          <li class=""><%= link_to 'About', home_about_path %></li>
          <li class=""><%= link_to 'sign up', new_user_registration_path %></li>
          <li class=""><%= link_to 'login', new_user_session_path %></li>
        <%end%>
      </ul>
    <%= yield %>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-xs-3">
  <p id="notice"><%= notice %></p>
  <% if book.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <h2><%= book.errors.count %>error</h2>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h2>User info</h2>
    <div class="profile-container">
        <table class="table table-striped">
          <thead>
            <tr><%= attachment_image_tag user, :profile_image, size:"60x60", class: "img-circle pull-left profile-img", fallback:"no_image.jpg" %></tr>
            <tr>
              <th>name</th>
              <th><h6 class="profile-name"><%= user.name %></h6></th>
              <th colspan="3"></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><h6 class="profile-introduction"><%= user.introduction %></h6></th>
            </tr>
          </thead>
        </table>
        <button type="button" class="btn btn-default" aria-label="Left Align">
          <span class="glyphicon glyphicon-wrench" aria-hidden="true">
          <%= link_to 'Edit', edit_user_path(user) %>
          </span>
        </button>
    </div>
  <h2>New book</h2>
  <%= form_for(book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <br><%= f.submit 'Create Book' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-8">
<h2 id="notice"><%= notice %></h2>
<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <h2><%= @user.errors.count %>error</h2>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <h2>User info</h2>
    <%= form_for(@user) do |f| %>
      <h4>Name</h4>
      <%= f.text_field :name %>
      <h4>Image</h4>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
      <h4>Introduction</h4>
      <%= f.text_area :introduction %>
      <br><%= f.submit 'Update User' %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<%= render 'users/list', user: @user, book: @newbook %>
<div class="col-xs-9">
  <h2>Users</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size:"30x30", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'users/list', user: @user, book: @newbook %>
    <div class="col-xs-9">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', class: "img-circle pull-left profile-img" %>
                <% end %>
                </td>
              <td><%= link_to book do %><%= book.title %><% end %></td>
              <td><%= book.body %></td>
              <td><%= link_to 'Show', book %></td>
              <td><%= link_to 'Edit', edit_book_path(book) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/top.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4">
  <h1>welcome to Bookers !!</h1>
  <h4>In Bookers,<br>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</h4>
  <div class="btn-group-vertical" role="group">
    <button type="button" class="btn btn-default" >
      <%= link_to 'Log in', new_user_session_path %>
    </button>
    <button type="button" class="btn btn-default">
      <%= link_to 'Sign Up', new_user_registration_path %>
    </button>
  </div>
</div>
<div class="col-lg-4"></div>